// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZgsvT0YCG_CxkTs8I6vUZw0bLHUDvV8U',
    appId: '1:467258086673:web:751c89fa232bf716cd28b0',
    messagingSenderId: '467258086673',
    projectId: 'giuple-b4369',
    authDomain: 'giuple-b4369.firebaseapp.com',
    storageBucket: 'giuple-b4369.firebasestorage.app',
    measurementId: 'G-TY0Z12MYWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhNxhgUFD2JslDaJUrLZ1vcaKHr4IIbDo',
    appId: '1:467258086673:android:12d49df65c4ed656cd28b0',
    messagingSenderId: '467258086673',
    projectId: 'giuple-b4369',
    storageBucket: 'giuple-b4369.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl17_5BQslHkxecN52eu0AsqTU-RVGeo4',
    appId: '1:467258086673:ios:c4aac64934df992acd28b0',
    messagingSenderId: '467258086673',
    projectId: 'giuple-b4369',
    storageBucket: 'giuple-b4369.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl17_5BQslHkxecN52eu0AsqTU-RVGeo4',
    appId: '1:467258086673:ios:c4aac64934df992acd28b0',
    messagingSenderId: '467258086673',
    projectId: 'giuple-b4369',
    storageBucket: 'giuple-b4369.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZgsvT0YCG_CxkTs8I6vUZw0bLHUDvV8U',
    appId: '1:467258086673:web:11e34c9d5bafd3b5cd28b0',
    messagingSenderId: '467258086673',
    projectId: 'giuple-b4369',
    authDomain: 'giuple-b4369.firebaseapp.com',
    storageBucket: 'giuple-b4369.firebasestorage.app',
    measurementId: 'G-YY7W9W24HK',
  );

}